---
root: true

env:
  browser: true
  node: true
  es6: true

settings:
  ecmascript: 6

plugins:
  - react

parser:
  "babel-eslint"

extends:
  - airbnb

rules:
  strict: 2
  quotes:
    - 2
    - single
